title: CompSci Blogs
description: "August 2023 to November 2023"
owner_name: Bhouvanamohini-Vrnda Kanhye
github_username: nighthawkcoders
baseurl: "/bvk-csse-1"
# remote_theme: pages-themes/midnight@v0.2.0 
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
